# Generated by Django 2.2.12 on 2025-05-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
