# Generated by Django 4.2.23 on 2025-06-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='data_publicacao',
        ),
        migrations.AddField(
            model_name='livro',
            name='ano_publicacao',
            field=models.IntegerField(default=2025),
        ),
    ]
