# Generated by Django 4.2.23 on 2025-06-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_remove_livro_data_publicacao_livro_ano_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.CharField(choices=[('ficcao', 'Ficção'), ('romance', 'Romance'), ('aventura', 'Aventura'), ('fantasia', 'Fantasia'), ('biografia', 'Biografia'), ('autoajuda', 'Autoajuda'), ('tecnico', 'Técnico')], default='ficcao', max_length=20),
        ),
        migrations.AddField(
            model_name='livro',
            name='isbn',
            field=models.CharField(blank=True, help_text='ISBN do livro (ex: 978-3-16-148410-0)', max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
