# Generated by Django 4.2.23 on 2025-06-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cliente_email'),
        ('livros', '0005_reserva_data_devolucao_alter_reserva_data_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='data_devolucao',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='data_reserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_solicitacao',
            field=models.DateField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('FINALIZADA', 'Finalizada')], default='AGUARDANDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.CharField(choices=[('FICCAO', 'Ficção'), ('ROMANCE', 'Romance'), ('AVENTURA', 'Aventura'), ('FANTASIA', 'Fantasia'), ('BIOFRAFIA', 'Biografia'), ('AUTOAJUDA', 'Autoajuda'), ('TECNICO', 'Técnico')], default='ficcao', max_length=20),
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao', models.DateField()),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado'), ('EM_ATRASO', 'Em Atraso')], default='EM_ANDAMENTO', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.livro')),
            ],
        ),
    ]
