# Generated by Django 4.2.23 on 2025-06-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_infracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='infracao',
            name='bloquear_cliente',
            field=models.BooleanField(default=True),
        ),
    ]
