# Generated by Django 4.2.23 on 2025-06-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0008_infracao_bloquear_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='infracao',
            name='data_infracao',
            field=models.DateField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
    ]
