# Generated by Django 5.2.3 on 2025-07-03 00:12

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0009_infracao_data_infracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='url',
        ),
        migrations.AddField(
            model_name='livro',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='fotos/alunos', variations={'medium': (300, 300), 'thumb': (150, 150)}),
        ),
    ]
