# Generated by Django 2.2.12 on 2025-05-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=30)),
                ('logradouro', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=30)),
            ],
        ),
    ]
