# Generated by Django 4.2.23 on 2025-06-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
    ]
